simple_user_password_reset:
    path: /password/reset/{passwordResetHash}
    controller: SimpleUser\Controller\PasswordResetController::index

simple_user_forgot_password:
    path: /forgot/password
    controller: SimpleUser\Controller\PasswordResetController::askNewPasswordResetLink