simple_user_login:
    path: /login
    controller: SimpleUser\Controller\SecurityController::login

simple_user_login_check:
    path: /login_check
    controller: SimpleUser\Controller\SecurityController::loginCheck

simple_user_logout:
    path: /logout
    controller: SimpleUser\Controller\SecurityController::logout

simple_user_registration:
    path: /registration
    controller: SimpleUser\Controller\RegistrationController::index

simple_user_registration_complete:
    path: /registration/complete/{confirmHash}
    controller: SimpleUser\Controller\RegistrationController::complete