services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    SimpleUser\Controller\:
        resource: './../../Controller'
        tags: ['controller.service_arguments']

    simple_user.user_manager:
        class: SimpleUser\Service\UserManager
        arguments: ['@doctrine.orm.entity_manager','%simple_user.user_class%', '%simple_user.role_class%']

    simple_user.password_subscriber:
        class: SimpleUser\Events\UserPasswordSubscriber
        arguments: ['@security.encoder_factory']
        tags:
          - { name: doctrine.event_subscriber, connection: default }

    SimpleUser\Command\AddRoleToUserCommand:
        calls:
          - method: setUserManager
            arguments:
              - '@simple_user.user_manager'
        tags:
            - { name: 'console.command', command: 'simple-user:add-role' }
    SimpleUser\Command\RemoveRoleFromUserCommand:
        calls:
          - method: setUserManager
            arguments:
              - '@simple_user.user_manager'
        tags:
            - { name: 'console.command', command: 'simple-user:remove-role' }
    SimpleUser\Command\CreateUserCommand:
        calls:
          - method: setUserManager
            arguments:
              - '@simple_user.user_manager'
        tags:
            - { name: 'console.command', command: 'simple-user:create' }