services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    SimpleUser\Controller\:
        resource: './../../Controller'
        tags: ['controller.service_arguments']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SimpleUser\:
        resource: './../../*'
        exclude: './../../{Model,Migrations,Tests,Kernel.php}'

    simple_user.user_manager:
        class: SimpleUser\Service\UserManager
        arguments: ['@doctrine.orm.entity_manager','%simple_user.user_class%', '%simple_user.role_class%']

    simple_user.password_subscriber:
        class: SimpleUser\Events\UserPasswordSubscriber
        arguments: ['@security.encoder_factory']
        tags:
          - { name: doctrine.event_subscriber, connection: default }

    simple_user.command.add_role:
        class: SimpleUser\Command\AddRoleToUserCommand
        tags:
            - { name: 'console.command' }
    simple_user.command.remove_role:
        class: SimpleUser\Command\RemoveRoleFromUserCommand
        tags:
            - { name: 'console.command' }
    simple_user.command.create:
        class: SimpleUser\Command\CreateUserCommand
        tags:
            - { name: 'console.command' }